/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentDBMysql;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tusha
 */
public class StudentDBMysql extends javax.swing.JFrame {

    private static final String username="root";
    private static final String password="1234";
    private static final String dataConn="jdbc:mysql://localhost:3306/studentdata";
    
    Connection sqlConn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
     /* Creates new form StudentDBMysql
     */
    public StudentDBMysql() {
        initComponents();
        updateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // --------------------------------------FUNCTION DECLARATION---------------------------------------
    
    public void updateDB()
    {
    	int q,i;
    	
    	  try
          {
              Class.forName("com.mysql.jdbc.Driver");
              sqlConn =DriverManager.getConnection(dataConn,username,password);
              pst=sqlConn.prepareStatement("select * from studentdata");
             
              rs=pst.executeQuery();
              ResultSetMetaData StData=rs.getMetaData();
               q=StData.getColumnCount();	
               
               DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
               RecordTable.setRowCount(0);
               
               while(rs.next())
               {
            	   Vector columnData= new Vector();
            	   	
            	   for(i=1;i<=q;i++)
            	   {
            		   columnData.add(rs.getString("id"));
            		   columnData.add(rs.getString("studentid"));
            		   columnData.add(rs.getString("firstname"));
            		   columnData.add(rs.getString("lastname"));
            		   columnData.add(rs.getString("address"));
            		   columnData.add(rs.getString("gender"));
            		   columnData.add(rs.getString("mobile"));
            		   columnData.add(rs.getString("java"));
            		   columnData.add(rs.getString("operatingsystem"));
            		   columnData.add(rs.getString("dbms"));
            		   columnData.add(rs.getString("management"));
            		   columnData.add(rs.getString("semiconductor"));
            		   columnData.add(rs.getString("probability"));
            		   columnData.add(rs.getString("constitution"));
            		   columnData.add(rs.getString("psychology"));
            		   columnData.add(rs.getString("humanvalues"));
            		   columnData.add(rs.getString("literature"));
            		   
            		  
            	   }
            	   RecordTable.addRow(columnData); 
               }
               
         }
          catch ( Exception ex ) {
             JOptionPane.showMessageDialog(null,ex);
          }
    }
    
    
    
    
    
    
    
    //--------------------------------------------------------------------------------------------------
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        cboGen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtMob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cboJava = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboOs = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboDbms = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboMgment = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cboSemi = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cboPsy = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cboHv = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cboProb = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cboLite = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cboCons = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setForeground(new java.awt.Color(95, 158, 160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("STUDENT ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        txtSid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSidActionPerformed(evt);
            }
        });
        jPanel2.add(txtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 290, -1));

        cboGen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        cboGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGenActionPerformed(evt);
            }
        });
        jPanel2.add(cboGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("FIRST NAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        txtFname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 290, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LAST NAME");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));

        txtLname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 290, -1));

        txtMob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobActionPerformed(evt);
            }
        });
        jPanel2.add(txtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("MOBILE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 80, 30));

        txtAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });
        jPanel2.add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 290, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText(" ADDRESS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("GENDER");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 30));

        jPanel6.setBackground(new java.awt.Color(51, 255, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ADVANCE JAVA");

        cboJava.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboJava.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));
        cboJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJavaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText(" OPERATING SYSTEM");

        cboOs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboOs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("DBMS");

        cboDbms.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboDbms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("MANAGEMENT");

        cboMgment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboMgment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("SEMI-CONDUCTOR");

        cboSemi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboSemi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboJava, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboOs, 0, 86, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboDbms, 0, 86, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMgment, 0, 86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboSemi, 0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboJava, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboOs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboDbms, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboMgment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 250));

        jPanel7.setBackground(new java.awt.Color(51, 255, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("PSYCHOLOGY");

        cboPsy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboPsy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(" HUMAN VALUES");

        cboHv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboHv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("PROBABILITY");

        cboProb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboProb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("LITERATURE");

        cboLite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboLite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText(" INDIAN CONSTITUTION");

        cboCons.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboCons.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES", "NOT QUALIFIED" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboHv, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboPsy, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLite, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cboCons, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cboProb, 0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboProb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCons, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboPsy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboHv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboLite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 200, 250));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 480));

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Student ID", "First Name", "Last Name", "Address", "Gender", "Mobile", "Advance Java", "Operating System", "DBMS", "Management", "Semi-Conductor", "Probability", "Indian Constitution", "Psychology", "Human Values", "LITERATURE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 940, 450));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 960, 480));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(0, 255, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton11.setText("ADD NEW");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 100));

        jButton12.setBackground(new java.awt.Color(0, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton12.setText("EXIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 210, 100));

        jButton14.setBackground(new java.awt.Color(0, 255, 255));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton14.setText("DELETE");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 210, 100));

        jButton15.setBackground(new java.awt.Color(0, 255, 255));
        jButton15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton15.setText("RESET");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 210, 100));

        jButton16.setBackground(new java.awt.Color(0, 255, 255));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton16.setText("UPDATE");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 210, 100));

        jButton17.setBackground(new java.awt.Color(0, 255, 255));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton17.setText("PRINT");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 210, 100));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1410, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1440, 660));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(102, 255, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("STUDENT DATABASE MANAGEMENT SYSTEM");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1380, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1440, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn =DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("insert into studentdata(studentid,firstname,lastname,address,gender,mobile,java,operatingsystem,dbms,management,semiconductor,probability,constitution,psychology,humanvalues,literature)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
           
            pst.setString(1,txtSid.getText());
            pst.setString(2,txtFname.getText());
            pst.setString(3,txtLname.getText());
            pst.setString(4,txtAdd.getText());
            pst.setString(5,(String)cboGen.getSelectedItem());
            pst.setString(6,txtMob.getText());
            pst.setString(7,(String)cboJava.getSelectedItem());
            pst.setString(8,(String)cboOs.getSelectedItem());
            pst.setString(9,(String)cboDbms.getSelectedItem());
            pst.setString(10,(String)cboMgment.getSelectedItem());
            pst.setString(11,(String)cboSemi.getSelectedItem());
            pst.setString(12,(String)cboProb.getSelectedItem());
            pst.setString(13,(String)cboCons.getSelectedItem());
            pst.setString(14,(String)cboPsy.getSelectedItem());
            pst.setString(15,(String)cboHv.getSelectedItem());
            pst.setString(16,(String)cboLite.getSelectedItem());
            
            pst.executeUpdate();  
            JOptionPane.showMessageDialog(this,"Student Record Added");
            updateDB();
       }
        catch ( SQLException ex ) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentDBMysql.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    }//GEN-LAST:event_jButton11ActionPerformed
private JFrame frame;
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
            frame = new JFrame("EXIT");
            if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Student Database Management System",
                    JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
        
           DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
       int SelectedRows=jTable1.getSelectedRow();
       
       
         try
        {
            int id=Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            
            int DeleteItem=JOptionPane.showConfirmDialog(null,"Confirm if u want to delete item","Warning",JOptionPane.YES_NO_OPTION);
            if(DeleteItem==JOptionPane.YES_OPTION)
            {
            
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn =DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("delete from studentdata where id=?");
                 
            pst.setInt(1,id);
               pst.executeUpdate();  
            JOptionPane.showMessageDialog(this,"Student Record Updateded");
            updateDB();      
            
            
           txtSid.setText("");
           txtSid.requestFocus();
            txtFname.setText("");
            txtLname.setText("");
            txtAdd.setText("");
            cboGen.setSelectedIndex(0);
            txtMob.setText("");
            cboJava.setSelectedIndex(0);
            cboOs.setSelectedIndex(0);
            cboDbms.setSelectedIndex(0);
            cboMgment.setSelectedIndex(0);
            cboSemi.setSelectedIndex(0);
            cboProb.setSelectedIndex(0);
            cboCons.setSelectedIndex(0);
            cboPsy.setSelectedIndex(0);
            cboHv.setSelectedIndex(0);
            cboLite.setSelectedIndex(0);
            }
         
       }
        catch ( SQLException ex ) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentDBMysql.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

            txtSid.setText("");
            txtFname.setText("");
            txtLname.setText("");
            txtAdd.setText("");
            cboGen.setSelectedIndex(0);
            txtMob.setText("");
            cboJava.setSelectedIndex(0);
            cboOs.setSelectedIndex(0);
            cboDbms.setSelectedIndex(0);
            cboMgment.setSelectedIndex(0);
            cboSemi.setSelectedIndex(0);
            cboProb.setSelectedIndex(0);
            cboCons.setSelectedIndex(0);
            cboPsy.setSelectedIndex(0);
            cboHv.setSelectedIndex(0);
            cboLite.setSelectedIndex(0);
           
            DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      
        DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
       int SelectedRows=jTable1.getSelectedRow();
       
       
         try
        {
            int id=Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn =DriverManager.getConnection(dataConn,username,password);
            pst=sqlConn.prepareStatement("update studentdata set studentid=? ,firstname=?, lastname=?,address=?,gender=?,mobile=?,java=?,operatingsystem=?,dbms=?,management=?,semiconductor=?,probability=?,constitution=?,psychology=?,humanvalues=?,literature=? where id=?");
                    
                    
            pst.setString(1,txtSid.getText());
            pst.setString(2,txtFname.getText());
            pst.setString(3,txtLname.getText());
            pst.setString(4,txtAdd.getText());
            pst.setString(5,(String)cboGen.getSelectedItem());
            pst.setString(6,txtMob.getText());
            pst.setString(7,(String)cboJava.getSelectedItem());
            pst.setString(8,(String)cboOs.getSelectedItem());
            pst.setString(9,(String)cboDbms.getSelectedItem());
            pst.setString(10,(String)cboMgment.getSelectedItem());
            pst.setString(11,(String)cboSemi.getSelectedItem());
            pst.setString(12,(String)cboProb.getSelectedItem());
            pst.setString(13,(String)cboCons.getSelectedItem());
            pst.setString(14,(String)cboPsy.getSelectedItem());
            pst.setString(15,(String)cboHv.getSelectedItem());
            pst.setString(16,(String)cboLite.getSelectedItem());
            pst.setInt(17,id);
            
            pst.executeUpdate();  
            JOptionPane.showMessageDialog(this,"Student Record Updateded");
            updateDB();
       }
        catch ( SQLException ex ) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentDBMysql.class.getName()).log(Level.SEVERE, null, ex);
        } 
         
         
       
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       MessageFormat header=new MessageFormat("Printing in process");
        MessageFormat footer=new MessageFormat("Page {0,number,integer");
        
        try 
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer Found",e.getMessage());
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void txtSidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSidActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddActionPerformed

    private void cboJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboJavaActionPerformed

    private void cboGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGenActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        
        DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
       int SelectedRows=jTable1.getSelectedRow();
       
       
       txtSid.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
       txtFname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
       txtLname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
       txtAdd.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
       cboGen.setSelectedItem(RecordTable.getValueAt(SelectedRows, 5).toString());
       txtMob.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
       cboJava.setSelectedItem(RecordTable.getValueAt(SelectedRows, 7).toString());
       cboOs.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
       cboDbms.setSelectedItem(RecordTable.getValueAt(SelectedRows, 9).toString());
       cboMgment.setSelectedItem(RecordTable.getValueAt(SelectedRows, 10).toString());
       cboSemi.setSelectedItem(RecordTable.getValueAt(SelectedRows, 11).toString());cboGen.setSelectedItem(RecordTable.getValueAt(SelectedRows, 1).toString());
       cboProb.setSelectedItem(RecordTable.getValueAt(SelectedRows, 12).toString());
       cboCons.setSelectedItem(RecordTable.getValueAt(SelectedRows, 13).toString());
       cboPsy.setSelectedItem(RecordTable.getValueAt(SelectedRows, 14).toString());
       cboHv.setSelectedItem(RecordTable.getValueAt(SelectedRows, 15).toString());
       cboLite.setSelectedItem(RecordTable.getValueAt(SelectedRows, 16).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDBMysql().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCons;
    private javax.swing.JComboBox<String> cboDbms;
    private javax.swing.JComboBox<String> cboGen;
    private javax.swing.JComboBox<String> cboHv;
    private javax.swing.JComboBox<String> cboJava;
    private javax.swing.JComboBox<String> cboLite;
    private javax.swing.JComboBox<String> cboMgment;
    private javax.swing.JComboBox<String> cboOs;
    private javax.swing.JComboBox<String> cboProb;
    private javax.swing.JComboBox<String> cboPsy;
    private javax.swing.JComboBox<String> cboSemi;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMob;
    private javax.swing.JTextField txtSid;
    // End of variables declaration//GEN-END:variables
}
